# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_interface import robot_controller_pb2 as robot__controller__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in robot_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControllerStub(object):
    """Servicio disponible para el cliente (Blazor)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConectingSequence = channel.unary_unary(
                '/robot.RobotController/ConectingSequence',
                request_serializer=robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=robot__controller__pb2.Status.FromString,
                _registered_method=True)
        self.StopSequence = channel.unary_unary(
                '/robot.RobotController/StopSequence',
                request_serializer=robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=robot__controller__pb2.Status.FromString,
                _registered_method=True)
        self.ReferenceSequence = channel.unary_unary(
                '/robot.RobotController/ReferenceSequence',
                request_serializer=robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=robot__controller__pb2.Status.FromString,
                _registered_method=True)


class RobotControllerServicer(object):
    """Servicio disponible para el cliente (Blazor)
    """

    def ConectingSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    

    def StopSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReferenceSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConectingSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.ConectingSequence,
                    request_deserializer=robot__controller__pb2.Empty.FromString,
                    response_serializer=robot__controller__pb2.Status.SerializeToString,
            ),
            'StopSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSequence,
                    request_deserializer=robot__controller__pb2.Empty.FromString,
                    response_serializer=robot__controller__pb2.Status.SerializeToString,
            ),
            'ReferenceSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.ReferenceSequence,
                    request_deserializer=robot__controller__pb2.Empty.FromString,
                    response_serializer=robot__controller__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.RobotController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.RobotController', rpc_method_handlers)



 # This class is part of an EXPERIMENTAL API.
class RobotController(object):
    """Servicio disponible para el cliente (Blazor)
    """

    @staticmethod
    def ConectingSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/ConectingSequence',
            robot__controller__pb2.Empty.SerializeToString,
            robot__controller__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/StopSequence',
            robot__controller__pb2.Empty.SerializeToString,
            robot__controller__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReferenceSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/ReferenceSequence',
            robot__controller__pb2.Empty.SerializeToString,
            robot__controller__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
