# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_interface import robot_controller_pb2 as grpc__interface_dot_robot__controller__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_interface/robot_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConectingSequence = channel.unary_unary(
                '/robot.RobotController/ConectingSequence',
                request_serializer=grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=grpc__interface_dot_robot__controller__pb2.Status.FromString,
                _registered_method=True)
        self.GetConnectionStatuses = channel.unary_unary(
                '/robot.RobotController/GetConnectionStatuses',
                request_serializer=grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=grpc__interface_dot_robot__controller__pb2.RobotStatusList.FromString,
                _registered_method=True)
        self.ReferenceSequence = channel.unary_unary(
                '/robot.RobotController/ReferenceSequence',
                request_serializer=grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=grpc__interface_dot_robot__controller__pb2.Status.FromString,
                _registered_method=True)
        self.ReferenceSingle = channel.unary_unary(
                '/robot.RobotController/ReferenceSingle',
                request_serializer=grpc__interface_dot_robot__controller__pb2.RobotIdRequest.SerializeToString,
                response_deserializer=grpc__interface_dot_robot__controller__pb2.Status.FromString,
                _registered_method=True)
        self.GetReferenceStatuses = channel.unary_unary(
                '/robot.RobotController/GetReferenceStatuses',
                request_serializer=grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=grpc__interface_dot_robot__controller__pb2.RobotReferenceList.FromString,
                _registered_method=True)
        self.ImportVariables = channel.unary_unary(
                '/robot.RobotController/ImportVariables',
                request_serializer=grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=grpc__interface_dot_robot__controller__pb2.Status.FromString,
                _registered_method=True)
        self.GetImportVariableStatuses = channel.unary_unary(
                '/robot.RobotController/GetImportVariableStatuses',
                request_serializer=grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=grpc__interface_dot_robot__controller__pb2.RobotImportStatusList.FromString,
                _registered_method=True)
        self.StartSequence = channel.unary_unary(
                '/robot.RobotController/StartSequence',
                request_serializer=grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=grpc__interface_dot_robot__controller__pb2.Status.FromString,
                _registered_method=True)
        self.PauseSequence = channel.unary_unary(
                '/robot.RobotController/PauseSequence',
                request_serializer=grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=grpc__interface_dot_robot__controller__pb2.Status.FromString,
                _registered_method=True)
        self.ResumeSequence = channel.unary_unary(
                '/robot.RobotController/ResumeSequence',
                request_serializer=grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=grpc__interface_dot_robot__controller__pb2.Status.FromString,
                _registered_method=True)
        self.StopSequence = channel.unary_unary(
                '/robot.RobotController/StopSequence',
                request_serializer=grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
                response_deserializer=grpc__interface_dot_robot__controller__pb2.Status.FromString,
                _registered_method=True)


class RobotControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConectingSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectionStatuses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReferenceSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReferenceSingle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReferenceStatuses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImportVariableStatuses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConectingSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.ConectingSequence,
                    request_deserializer=grpc__interface_dot_robot__controller__pb2.Empty.FromString,
                    response_serializer=grpc__interface_dot_robot__controller__pb2.Status.SerializeToString,
            ),
            'GetConnectionStatuses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectionStatuses,
                    request_deserializer=grpc__interface_dot_robot__controller__pb2.Empty.FromString,
                    response_serializer=grpc__interface_dot_robot__controller__pb2.RobotStatusList.SerializeToString,
            ),
            'ReferenceSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.ReferenceSequence,
                    request_deserializer=grpc__interface_dot_robot__controller__pb2.Empty.FromString,
                    response_serializer=grpc__interface_dot_robot__controller__pb2.Status.SerializeToString,
            ),
            'ReferenceSingle': grpc.unary_unary_rpc_method_handler(
                    servicer.ReferenceSingle,
                    request_deserializer=grpc__interface_dot_robot__controller__pb2.RobotIdRequest.FromString,
                    response_serializer=grpc__interface_dot_robot__controller__pb2.Status.SerializeToString,
            ),
            'GetReferenceStatuses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReferenceStatuses,
                    request_deserializer=grpc__interface_dot_robot__controller__pb2.Empty.FromString,
                    response_serializer=grpc__interface_dot_robot__controller__pb2.RobotReferenceList.SerializeToString,
            ),
            'ImportVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportVariables,
                    request_deserializer=grpc__interface_dot_robot__controller__pb2.Empty.FromString,
                    response_serializer=grpc__interface_dot_robot__controller__pb2.Status.SerializeToString,
            ),
            'GetImportVariableStatuses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImportVariableStatuses,
                    request_deserializer=grpc__interface_dot_robot__controller__pb2.Empty.FromString,
                    response_serializer=grpc__interface_dot_robot__controller__pb2.RobotImportStatusList.SerializeToString,
            ),
            'StartSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSequence,
                    request_deserializer=grpc__interface_dot_robot__controller__pb2.Empty.FromString,
                    response_serializer=grpc__interface_dot_robot__controller__pb2.Status.SerializeToString,
            ),
            'PauseSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseSequence,
                    request_deserializer=grpc__interface_dot_robot__controller__pb2.Empty.FromString,
                    response_serializer=grpc__interface_dot_robot__controller__pb2.Status.SerializeToString,
            ),
            'ResumeSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeSequence,
                    request_deserializer=grpc__interface_dot_robot__controller__pb2.Empty.FromString,
                    response_serializer=grpc__interface_dot_robot__controller__pb2.Status.SerializeToString,
            ),
            'StopSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSequence,
                    request_deserializer=grpc__interface_dot_robot__controller__pb2.Empty.FromString,
                    response_serializer=grpc__interface_dot_robot__controller__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.RobotController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.RobotController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConectingSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/ConectingSequence',
            grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
            grpc__interface_dot_robot__controller__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectionStatuses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/GetConnectionStatuses',
            grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
            grpc__interface_dot_robot__controller__pb2.RobotStatusList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReferenceSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/ReferenceSequence',
            grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
            grpc__interface_dot_robot__controller__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReferenceSingle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/ReferenceSingle',
            grpc__interface_dot_robot__controller__pb2.RobotIdRequest.SerializeToString,
            grpc__interface_dot_robot__controller__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReferenceStatuses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/GetReferenceStatuses',
            grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
            grpc__interface_dot_robot__controller__pb2.RobotReferenceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/ImportVariables',
            grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
            grpc__interface_dot_robot__controller__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImportVariableStatuses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/GetImportVariableStatuses',
            grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
            grpc__interface_dot_robot__controller__pb2.RobotImportStatusList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/StartSequence',
            grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
            grpc__interface_dot_robot__controller__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/PauseSequence',
            grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
            grpc__interface_dot_robot__controller__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/ResumeSequence',
            grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
            grpc__interface_dot_robot__controller__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.RobotController/StopSequence',
            grpc__interface_dot_robot__controller__pb2.Empty.SerializeToString,
            grpc__interface_dot_robot__controller__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
