syntax = "proto3";

package robot;


service RobotController {
  rpc ConectingSequence(Empty) returns (Status);
  rpc ReferenceSequence(Empty) returns (Status);     
  rpc ReferenceSingle(RobotIdRequest) returns (Status);
  rpc StartSequence(Empty) returns (Status);
  rpc PauseSequence(Empty) returns (Status);
  rpc ResumeSequence(Empty) returns (Status);
  rpc StopSequence(Empty) returns (Status);
}

message Empty {}

message Status {
  string message = 1;
  bool success = 2;
}

message RobotIdRequest {
  string robot_id = 1;
}