# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot_controller.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'robot_controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16robot_controller.proto\x12\x05robot\"\x07\n\x05\x45mpty\"*\n\x06Status\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xa2\x01\n\x0fRobotController\x12\x30\n\x11\x43onectingSequence\x12\x0c.robot.Empty\x1a\r.robot.Status\x12+\n\x0cStopSequence\x12\x0c.robot.Empty\x1a\r.robot.Status\x12\x30\n\x11ReferenceSequence\x12\x0c.robot.Empty\x1a\r.robot.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=33
  _globals['_EMPTY']._serialized_end=40
  _globals['_STATUS']._serialized_start=42
  _globals['_STATUS']._serialized_end=84
  _globals['_ROBOTCONTROLLER']._serialized_start=87
  _globals['_ROBOTCONTROLLER']._serialized_end=249
# @@protoc_insertion_point(module_scope)
